### ISSUE TITLE
Unable to compile the project

### ISSUE THREAD

**Issue by ajaywazir** [itldg/MauiUsbSerialForAndroid#1]
Hi
I tried to test this project. I get this error
Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2098	xml_microsoft_maui_essentials_fileprovider_file_paths.xml.flat: error: failed to open file. "xml_microsoft_maui_essentials_fileprovider_file_paths.xml.flat: error: failed to open file.".	MauiUsbSerialForAndroid	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Aapt2.targets	123	

What could be the reasons
I am using VS2022 Community Edition
Regards
Ajay

**Comment by itldg** [comment]
Microsoft Visual Studio Community 2022 (64 位) - Current

This is the version I use. I just pulled the code and the generation went well

**Comment by itldg** [comment]
If there is no more to add, I will close the Issues
